/// A type that represents a country according to ISO 3166-1 alpha-2.
public enum Country: String, Hashable, Sendable, CaseIterable, Codable {
    case ad, ae, af, ag, ai, al, am, ao, aq, ar, `as`, at, au, aw, ax, az
    case ba, bb, bd, be, bf, bg, bh, bi, bj, bl, bm, bn, bo, bq, br, bs, bt, bv, bw, by, bz
    case ca, cc, cd, cf, cg, ch, ci, ck, cl, cm, cn, co, cr, cu, cv, cw, cx, cy, cz
    case de, dj, dk, dm, `do`, dz
    case ec, ee, eg, eh, er, es, et
    case fi, fj, fk, fm, fo, fr
    case ga, gb, gd, ge, gf, gg, gh, gi, gl, gm, gn, gp, gq, gr, gs, gt, gu, gw, gy
    case hk, hm, hn, hr, ht, hu
    case id, ie, il, im, `in`, io, iq, ir, `is`, it
    case je, jm, jo, jp
    case ke, kg, kh, ki, km, kn, kp, kr, kw, ky, kz
    case la, lb, lc, li, lk, lr, ls, lt, lu, lv, ly
    case ma, mc, md, me, mf, mg, mh, mk, ml, mm, mn, mo, mp, mq, mr, ms, mt, mu, mv, mw, mx, my, mz
    case na, nc, ne, nf, ng, ni, nl, no, np, nr, nu, nz
    case om
    case pa, pe, pf, pg, ph, pk, pl, pm, pn, pr, ps, pt, pw, py
    case qa
    case re, ro, rs, ru, rw
    case sa, sb, sc, sd, se, sg, sh, si, sj, sk, sl, sm, sn, so, sr, ss, st, sv, sx, sy, sz
    case tc, td, tf, tg, th, tj, tk, tl, tm, tn, to, tr, tt, tv, tw, tz
    case ua, ug, um, us, uy, uz
    case va, vc, ve, vg, vi, vn, vu
    case wf, ws
    case ye, yt
    case za, zm, zw

    /// Human-readable country name, in English.
    public var name: String {
        switch self {
        case .ad: "Andorra"
        case .ae: "United Arab Emirates"
        case .af: "Afghanistan"
        case .ag: "Antigua and Barbuda"
        case .ai: "Anguilla"
        case .al: "Albania"
        case .am: "Armenia"
        case .ao: "Angola"
        case .aq: "Antarctica"
        case .ar: "Argentina"
        case .as: "American Samoa"
        case .at: "Austria"
        case .au: "Australia"
        case .aw: "Aruba"
        case .ax: "Aland Islands"
        case .az: "Azerbaijan"
        case .ba: "Bosnia and Herzegovina"
        case .bb: "Barbados"
        case .bd: "Bangladesh"
        case .be: "Belgium"
        case .bf: "Burkina Faso"
        case .bg: "Bulgaria"
        case .bh: "Bahrain"
        case .bi: "Burundi"
        case .bj: "Benin"
        case .bl: "Saint Barthelemy"
        case .bm: "Bermuda"
        case .bn: "Brunei Darussalam"
        case .bo: "Bolivia (Plurinational State of)"
        case .bq: "Bonaire, Sint Eustatius and Saba"
        case .br: "Brazil"
        case .bs: "Bahamas"
        case .bt: "Bhutan"
        case .bv: "Bouvet Island"
        case .bw: "Botswana"
        case .by: "Belarus"
        case .bz: "Belize"
        case .ca: "Canada"
        case .cc: "Cocos (Keeling) Islands"
        case .cd: "Congo, Democratic Republic of the"
        case .cf: "Central African Republic"
        case .cg: "Congo"
        case .ch: "Switzerland"
        case .ci: "Cote d'Ivoire"
        case .ck: "Cook Islands"
        case .cl: "Chile"
        case .cm: "Cameroon"
        case .cn: "China"
        case .co: "Colombia"
        case .cr: "Costa Rica"
        case .cu: "Cuba"
        case .cv: "Cabo Verde"
        case .cw: "Curacao"
        case .cx: "Christmas Island"
        case .cy: "Cyprus"
        case .cz: "Czechia"
        case .de: "Germany"
        case .dj: "Djibouti"
        case .dk: "Denmark"
        case .dm: "Dominica"
        case .do: "Dominican Republic"
        case .dz: "Algeria"
        case .ec: "Ecuador"
        case .ee: "Estonia"
        case .eg: "Egypt"
        case .eh: "Western Sahara"
        case .er: "Eritrea"
        case .es: "Spain"
        case .et: "Ethiopia"
        case .fi: "Finland"
        case .fj: "Fiji"
        case .fk: "Falkland Islands (Malvinas)"
        case .fm: "Micronesia (Federated States of)"
        case .fo: "Faroe Islands"
        case .fr: "France"
        case .ga: "Gabon"
        case .gb: "United Kingdom of Great Britain and Northern Ireland"
        case .gd: "Grenada"
        case .ge: "Georgia"
        case .gf: "French Guiana"
        case .gg: "Guernsey"
        case .gh: "Ghana"
        case .gi: "Gibraltar"
        case .gl: "Greenland"
        case .gm: "Gambia"
        case .gn: "Guinea"
        case .gp: "Guadeloupe"
        case .gq: "Equatorial Guinea"
        case .gr: "Greece"
        case .gs: "South Georgia and the South Sandwich Islands"
        case .gt: "Guatemala"
        case .gu: "Guam"
        case .gw: "Guinea-Bissau"
        case .gy: "Guyana"
        case .hk: "Hong Kong"
        case .hm: "Heard Island and McDonald Islands"
        case .hn: "Honduras"
        case .hr: "Croatia"
        case .ht: "Haiti"
        case .hu: "Hungary"
        case .id: "Indonesia"
        case .ie: "Ireland"
        case .il: "Israel"
        case .im: "Isle of Man"
        case .in: "India"
        case .io: "British Indian Ocean Territory"
        case .iq: "Iraq"
        case .ir: "Iran (Islamic Republic of)"
        case .is: "Iceland"
        case .it: "Italy"
        case .je: "Jersey"
        case .jm: "Jamaica"
        case .jo: "Jordan"
        case .jp: "Japan"
        case .ke: "Kenya"
        case .kg: "Kyrgyzstan"
        case .kh: "Cambodia"
        case .ki: "Kiribati"
        case .km: "Comoros"
        case .kn: "Saint Kitts and Nevis"
        case .kp: "Korea (Democratic People's Republic of)"
        case .kr: "Korea, Republic of"
        case .kw: "Kuwait"
        case .ky: "Cayman Islands"
        case .kz: "Kazakhstan"
        case .la: "Lao People's Democratic Republic"
        case .lb: "Lebanon"
        case .lc: "Saint Lucia"
        case .li: "Liechtenstein"
        case .lk: "Sri Lanka"
        case .lr: "Liberia"
        case .ls: "Lesotho"
        case .lt: "Lithuania"
        case .lu: "Luxembourg"
        case .lv: "Latvia"
        case .ly: "Libya"
        case .ma: "Morocco"
        case .mc: "Monaco"
        case .md: "Moldova, Republic of"
        case .me: "Montenegro"
        case .mf: "Saint Martin (French part)"
        case .mg: "Madagascar"
        case .mh: "Marshall Islands"
        case .mk: "North Macedonia"
        case .ml: "Mali"
        case .mm: "Myanmar"
        case .mn: "Mongolia"
        case .mo: "Macao"
        case .mp: "Northern Mariana Islands"
        case .mq: "Martinique"
        case .mr: "Mauritania"
        case .ms: "Montserrat"
        case .mt: "Malta"
        case .mu: "Mauritius"
        case .mv: "Maldives"
        case .mw: "Malawi"
        case .mx: "Mexico"
        case .my: "Malaysia"
        case .mz: "Mozambique"
        case .na: "Namibia"
        case .nc: "New Caledonia"
        case .ne: "Niger"
        case .nf: "Norfolk Island"
        case .ng: "Nigeria"
        case .ni: "Nicaragua"
        case .nl: "Netherlands"
        case .no: "Norway"
        case .np: "Nepal"
        case .nr: "Nauru"
        case .nu: "Niue"
        case .nz: "New Zealand"
        case .om: "Oman"
        case .pa: "Panama"
        case .pe: "Peru"
        case .pf: "French Polynesia"
        case .pg: "Papua New Guinea"
        case .ph: "Philippines"
        case .pk: "Pakistan"
        case .pl: "Poland"
        case .pm: "Saint Pierre and Miquelon"
        case .pn: "Pitcairn"
        case .pr: "Puerto Rico"
        case .ps: "Palestine, State of"
        case .pt: "Portugal"
        case .pw: "Palau"
        case .py: "Paraguay"
        case .qa: "Qatar"
        case .re: "Reunion"
        case .ro: "Romania"
        case .rs: "Serbia"
        case .ru: "Russian Federation"
        case .rw: "Rwanda"
        case .sa: "Saudi Arabia"
        case .sb: "Solomon Islands"
        case .sc: "Seychelles"
        case .sd: "Sudan"
        case .se: "Sweden"
        case .sg: "Singapore"
        case .sh: "Saint Helena, Ascension and Tristan da Cunha"
        case .si: "Slovenia"
        case .sj: "Svalbard and Jan Mayen"
        case .sk: "Slovakia"
        case .sl: "Sierra Leone"
        case .sm: "San Marino"
        case .sn: "Senegal"
        case .so: "Somalia"
        case .sr: "Suriname"
        case .ss: "South Sudan"
        case .st: "Sao Tome and Principe"
        case .sv: "El Salvador"
        case .sx: "Sint Maarten (Dutch part)"
        case .sy: "Syrian Arab Republic"
        case .sz: "Eswatini"
        case .tc: "Turks and Caicos Islands"
        case .td: "Chad"
        case .tf: "French Southern Territories"
        case .tg: "Togo"
        case .th: "Thailand"
        case .tj: "Tajikistan"
        case .tk: "Tokelau"
        case .tl: "Timor-Leste"
        case .tm: "Turkmenistan"
        case .tn: "Tunisia"
        case .to: "Tonga"
        case .tr: "Turkey"
        case .tt: "Trinidad and Tobago"
        case .tv: "Tuvalu"
        case .tw: "Taiwan, Province of China"
        case .tz: "Tanzania, United Republic of"
        case .ua: "Ukraine"
        case .ug: "Uganda"
        case .um: "United States Minor Outlying Islands"
        case .us: "United States of America"
        case .uy: "Uruguay"
        case .uz: "Uzbekistan"
        case .va: "Holy See"
        case .vc: "Saint Vincent and the Grenadines"
        case .ve: "Venezuela (Bolivarian Republic of)"
        case .vg: "Virgin Islands (British)"
        case .vi: "Virgin Islands (U.S.)"
        case .vn: "Viet Nam"
        case .vu: "Vanuatu"
        case .wf: "Wallis and Futuna"
        case .ws: "Samoa"
        case .ye: "Yemen"
        case .yt: "Mayotte"
        case .za: "South Africa"
        case .zm: "Zambia"
        case .zw: "Zimbabwe"
        }
    }
}
